### ISSUE TITLE
Feature: Add extra Actions

### ISSUE THREAD

**Issue by 4xel** [bitfocus/companion-module-resolume-arena#35]
- [x] - adjustCompositionOpacity
- [x] - adjustLayerOpacity
- [x] - adjustGroupOpacity
- [x] - adjustClipSpeed
- [x] - changeCompositionSpeed
- [x] #46
- [x] - controlLayerTransitionDuration
- [x] - controlClipTransport
- [x] - goToDeckIndex
- [x] - nextDeck
- [x] - previousDeck

**Comment by kman1898** [comment]
These would be amazing !

**Comment by kman1898** [comment]
Would love to see opacity added for sure

**Comment by 4xel** [comment]
adjustLayerOpacity done in #42

**Comment by 4xel** [comment]
adjustCompositionOpacity done in #43

**Comment by 4xel** [comment]
adjustGroupOpacity done in #44

**Comment by vjshaddow** [comment]
would be nice if we had the option to set the thumbnail aspect ratio. right now the image shows letterbox, would be nice to make the image cover the entire button.
<img width="237" alt="Screenshot 2024-02-18 184331" src="https://github.com/bitfocus/companion-module-resolume-arena/assets/141574914/8f52451c-4f8b-4f9b-92e0-ca4d62ccd13e">

**Comment by 4xel** [comment]
@vjshaddow I created a separate issue for this: #50 .
If I guess correctly the current image has the form of the thumbnail it has in resolume. Do you just want it to full the button?

**Comment by vjshaddow** [comment]
> @vjshaddow I created a separate issue for this: #50 . If I guess correctly the current image has the form of the thumbnail it has in resolume. Do you just want it to full the button?
did some more tests and the thumbnail does have the form of the content unless you upload a custom thumbnail but doing that for each clip is not feasible. i did noticed however that if the content itself is square it wont go full screen like a standard companion button would which in a way is good because if we add the Connected Clip feedback it will change the color of the outline like shown in the attached image 

![resolumefindings](https://github.com/bitfocus/companion-module-resolume-arena/assets/141574914/34063030-488a-4535-a547-5197fd1edf6b)

**Comment by 4xel** [comment]
@vjshaddow could you paste that in #50 ?

**Comment by 4xel** [comment]
![decks-all](https://github.com/bitfocus/companion-module-resolume-arena/assets/10220112/94df5dc2-7662-4f90-94da-6c19c45c5ea6)
added Next and Previous Deck + feedbacks + presets
